package com.example.pricingpal.model

import android.content.Context
import java.io.FileNotFoundException
import java.io.IOException
import java.io.InputStream
import java.io.InputStreamReader
import java.util.Scanner

/**
 * Class: CSVReader
 * @author Julian Ellis
 * @version 2.1
 * @written 9/24/2023
 * This object class holds a function to read a CSV file from the assets folder.
 */
object CSVReader {

    /**
     * readFile
     * This function reads a csv file into an ArrayList of Item objects.
     * @param fileName The name of the file to be read
     * @param c Context of the calling program (In MainActivity.kt use "this" keyword)
     * @return itemList The list of Item objects generated by the function
     */

}

